name: CD

on:
  push:
    branches: ['staging', 'production']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

    - name: create env file
      run: |
        if [ ${GITHUB_REF##*/} == "staging" ]
        then
          echo "$STAGING_ENV" > .env
        elif [ ${GITHUB_REF##*/} == "production" ]
        then
          echo "$PROD_ENV" > .env
        fi
      shell: bash
      env:
        STAGING_ENV: ${{secrets.STAGING_ENV}}
        PROD_ENV: ${{secrets.PROD_ENV}}

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 10.x

    - name: install packages
      run: npm install

    - name: check branch and deploy
      run: |
        if [ ${GITHUB_REF##*/} == "staging" ]
        then
          bash deploy-staging
        elif [ ${GITHUB_REF##*/} == "production" ]
        then
          bash deploy
        fi